services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "${CLIENT_PORT}:80"  # порт Vite
    volumes:
      - ./client:/app
    env_file:
      - ./client/.env
    depends_on:
      - server
    networks:
      - app-network  # Добавляем подключение к сети

  server:
    build: ./server
    ports:
      - "${SERVER_PORT}:3000"
    volumes:
      - server-data:/app/data # SQLite файл будет в /app/data внутри контейнера
    env_file:
      - ./server/.env
    restart: always
    networks:
      - app-network  # Добавляем подключение к сети

volumes:
  server-data:

networks:
  app-network:  # Определяем сеть