version: "3.8"

services:
  client:
    build: ./client
    ports:
      - "3000:80" # на 80-й порт контейнера попадает 3000 снаружи
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "4000:4000" # API на 4000
    volumes:
      - server-data:/app/data # SQLite файл будет в /app/data внутри контейнера
    restart: always

volumes:
  server-data:
